#!/bin/bash

NAME=$1

if [ -z "$NAME" ]; then
    echo "\033[31mUsage: mkclass ClassName\033[0m"
    exit 1
fi

if [ ! -d srcs ]; then
	mkdir srcs
fi

if [ ! -d inc ]; then
	mkdir inc
fi

HPP_FILE="inc/${NAME}.hpp"
CPP_FILE="srcs/${NAME}.cpp"
GUARD="$(echo ${NAME}_HPP | tr '[:lower:]' '[:upper:]')"

cat > $HPP_FILE <<EOF
#ifndef ${GUARD}
# define ${GUARD}

# include <iostream>				// ostream

class ${NAME}
{
	public:
		// Constructors
		${NAME}( void );
		${NAME}( const ${NAME} &cpy );

		// Arithmetic operators
		${NAME} &operator=( const ${NAME} &rhs );

		// Destructor
		~${NAME}( void );
	private:
		int	_data;
};

std::ostream &operator<<(std::ostream &out, const ${NAME} &obj);
#endif
EOF


cat > $CPP_FILE <<EOF
#include <iostream>		// cout
#include "${NAME}.hpp"

/* ****************************************************************************	*/
/*								CONSTRUCTORS				*/
/* ****************************************************************************	*/

${NAME}::${NAME} ( void ) : _data(0)
{
	//std::cout << "\033[90mDefault ${NAME} constructor called\033[0m" << std::endl;
	return ;
}

${NAME}::${NAME} ( const ${NAME} &cpy)
{
	//std::cout << "\033[90mCopy ${NAME} constructor called\033[0m" << std::endl;
	this->_data = cpy._data;
	return ;
}

/* ****************************************************************************	*/
/*								OPERATORS				*/
/* ****************************************************************************	*/

${NAME}	&${NAME}::operator=( const ${NAME}  &rhs )
{
	//std::cout << "\033[90mCopy ${NAME} operator called\033[0m" << std::endl;
	if (this == &rhs)
		return *this;
	this->_data = rhs._data;
	return *this;
}

/* ****************************************************************************	*/
/*								DESTRUCTOR				*/
/* ****************************************************************************	*/

${NAME}::~${NAME} ( void )
{
	//std::cout << "\033[90m${NAME} destructor called\033[0m" << std::endl;
	return ;
}

/* ****************************************************************************	*/
/*									GETERS				*/
/* ****************************************************************************	*/

/* ****************************************************************************	*/
/*									SETERS				*/
/* ****************************************************************************	*/

/* ****************************************************************************	*/
/*								MEMBER FUNCTIONS			*/
/* ****************************************************************************	*/

/* ****************************************************************************	*/
/*							NON MEMBER FUNCTIONS				*/
/* ****************************************************************************	*/
std::ostream	&operator<<(std::ostream &out, const ${NAME} &obj)
{
	(void)obj;
	out << "This is the overload of '<<' for the ${NAME} class" << std::endl;
	return out;
}
EOF

# Adds 42 header
vim -E -s -c "stdheader" -c "wq" "$HPP_FILE"

echo "Class ${NAME} created."
